apiVersion: v1
kind: Service
metadata:
  name: fyp-service
  namespace: default
spec:
  type: LoadBalancer
  selector:
    run: fyp
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
